name: testflight

on:
  push:
    branches: '**'
  pull_request:
    branches:
      - master

jobs:
  testflight_internal:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Xcode 11.4.1
      run: sudo xcode-select --switch /Applications/Xcode_11.4.app

    - name: Print env
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"